name: task_queue
description: |
  順番を保ったタスク実行を可能にする軽量なキューイングシステムを提供するDartパッケージです。
  非同期タスクの順序付き実行とタスクの完了待機をサポートします。
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/task_queue

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  synchronized: ^3.3.0+3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
