name: driftx
description: A starting point for Dart libraries or applications.
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/driftx

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.16.0
  drift: ^2.27.0
  drift_flutter: ^0.2.4
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
