name: datex
description: A starting point for Dart libraries or applications.
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/datex

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  time_machine: 0.9.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  loggerx: ^2025.1.1
