name: package_info_plus_riverpod
description: "A new Flutter package project."
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/package_info_plus_riverpod

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutterx: ^2025.1.1
  riverpodx: ^2025.1.1
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
