name: flutterx_riverpod
description: "A new Flutter package project."
version: 2025.1.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/flutterx_riverpod

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutterx: ^2025.1.0
  riverpodx: ^2025.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
