name: state_stream
description: "A new Flutter package project."
version: 2025.1.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/state_stream

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
