name: state_stream_riverpod
description: StateStream with Riverpod support.
version: 2.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  state_stream: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
