name: loggerx
description: A starting point for Dart libraries or applications.
version: 2025.1.0
repository: https://github.com/eaglesakura/flutter_armyknife/loggerx

environment:
  sdk: ">=3.6.0 <4.0.0"

resolution: workspace

dependencies:
  dartxx: ^2025.1.0
  logger: ^2.4.0
  platformx: ^1.1.0

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0 <2.0.0"
