name: riverpod_watch_plus
description: "A Flutter package that extends the ref.watch functionality of Riverpod."
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
