name: future_contextx
description: A starting point for Dart libraries or applications.
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/future_context

environment:
  sdk: ">=3.8.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  async_notify: ^0.0.2
  meta: ^1.16.0
  freezed_annotation: ^3.0.0
  runtime_assert: ^0.0.1+2
  future_context: ^0.0.2+13
  streamx: ^2025.1.1
  armyknife_dartx: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.0
  build_runner: ^2.5.2

dependency_overrides:
  rxdart: ^0.28.0
