name: armyknife_logger_grinder
description: Logger proxy for flutter.
version: 1.0.0
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

dependencies:
  armyknife_logger: ^1.0.1
  grinder: ^0.9.4

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
