name: armyknife_riverpodx
description: Flutter+Riverpod support library.
version: 2.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  hooks_riverpod: ^3.0.0
  flutter_hooks: ^0.21.3+1
  armyknife_flutterx: ^1.0.0
  armyknife_task_queue: ^1.0.0
  future_context2: ^1.0.1
  collection: ^1.19.1
  riverpod: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
