name: armyknife_yamlx
description: YamlX is a library for parsing and manipulating YAML files in Dart.
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  yaml: ^3.1.2
  armyknife_dartx: ^1.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
