name: definex
description: A sample command-line application.
version: 2025.1.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/definex

environment:
  sdk: ^3.6.0

dependencies:
  mustache_template: ^2.0.0
  grinder: ^0.9.5
  grinderx: ^2025.1.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
