name: armyknife_exceptions
description: Utilities for exceptions.
version: 1.0.0+2
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  collection: ^1.19.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
