name: flutter_bundle_loader
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/flutter_bundle_loader

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  data_reference: ^0.0.1+1

dev_dependencies:
  flutter_lints: ^6.0.0
