name: state_stream
description: Library for UI=f(State) architecture.
version: 1.0.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  async_notify2: ^1.0.0
  armyknife_dartx: ^1.0.0
  freezed_annotation: ^3.0.0
  future_context2: ^1.1.0
  meta: ^1.16.0
  runtime_assert: ^0.0.1+2
  rxdart: ^0.28.0
  armyknife_task_queue: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  freezed: ^3.0.0
  build_runner: ^2.5.2
