name: armyknife_logger
description: Simple Logger for Dart.
version: 1.0.1
repository: https://github.com/eaglesakura/flutter_armyknife/
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  armyknife_dartx: ^1.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^6.0.0
