name: armyknife_logger
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"

resolution: workspace

dependencies:
  armyknife_dartx: ^1.0.0
  logger: ^2.4.0
  platformx: ^1.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
