name: path_provider_riverpod
description: "A new Flutter package project."
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/path_provider_riverpod

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterx: ^2025.1.1
  riverpodx: ^2025.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
