name: riverpodx_test
description: "A new Flutter package project."
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  riverpodx: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
