name: riverpodx_test
description: "A new Flutter package project."
version: 2025.1.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/riverpodx_test

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  riverpodx: ^2025.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
