name: streamx
description: A starting point for Dart libraries or applications.
version: 2025.1.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/streamx

environment:
  sdk: ^3.6.0

dependencies:
  rxdart: ^0.28.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
