name: flutter_riverpod_watch_plus
description: "A library that enables DeepEquals support for Riverpod's Ref.watch()."
version: 2.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
