name: riverpod_container_async_test
description: riverpod_container_async test support library.
version: 2.0.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  riverpod: ^3.0.0
  flutter_riverpod: ^3.0.0
  riverpod_container_async: ^2.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
