name: armyknife_task_queue
description: |
  Light-Weight Task Queue for Dart.
version: 1.0.0
repository: https://github.com/eaglesakura/flutter_armyknife
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  synchronized: ^3.3.0+3

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
