name: grinderx
description: A starting point for Dart libraries or applications.
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/grinderx

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  grinder: ^0.9.5
  dartx: 1.2.0
  yaml: ^3.1.2
  yaml_writer: ^2.0.1
  properties: ^2.1.1
  yamlx: ^2025.1.1
  path: ^1.9.1
  dartxx: ^2025.1.1
  loggerx: ^2025.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
