name: armyknife_dartx
description: Dart runtime extensions.
version: 1.0.0
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/

environment:
  sdk: ">=3.8.0 <4.0.0"

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0
