name: intlx_generator
description: A starting point for Dart libraries or applications.
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/intlx_generator

environment:
  sdk: ^3.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  csv2arb: ^2025.1.1
  grinderx: ^2025.1.1
  mustache_template: ^2.0.0
  grinder: ^0.9.5
