name: armyknife_test_context
description: |
  Context object that guarantees one instance per Unit Test.
version: 1.0.0
repository: https://github.com/eaglesakura/flutter_armyknife/
resolution: workspace

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
