name: yamlx
description: A starting point for Dart libraries or applications.
version: 2025.1.1
resolution: workspace
repository: https://github.com/eaglesakura/flutter_armyknife/yamlx

environment:
  sdk: ^3.6.0

dependencies:
  yaml: ^3.1.2
  dartxx: ^2025.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
